/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "uart.h"
#include "led.h"
#include <stdio.h>
#include <stdint.h>
#include "osKernel.h"
typedef uint32_t TaskProfiler;
TaskProfiler Task0_Profiler,Task1_Profiler,Task2_Profiler, pTask1_Profiler, pTask2_Profiler;
#define QUANTA 2
void motor_run(void);
void valve_open(void);
void valve_close(void);
void motor_stop(void);
int32_t semaphore1, semaphore2;



void task3(void){
	pTask1_Profiler++;
}
void task0(void){
	while(1){
		Task0_Profiler++;
		//osThreadYield();
	}
}
void task1(void){
	while(1){
		osSemaphoreWait(&semaphore1);
		valve_open();
		osSemaphoreSet(&semaphore1);
	}
}
void task2(void){
	while(1){
		osSemaphoreWait(&semaphore2);
		motor_run();
		osSemaphoreSet(&semaphore2);

	}
}
int main(void){
	//initialize kernel, and add threads

	uart_tx_init();
	tim2_1hz_interrupt_init();
	osSemaphoreInit(&semaphore1, 1);
	osSemaphoreInit(&semaphore2, 0);
	osKernelInit();
	osKernelAddThreads(&task0, &task1, &task2);
	osKernelLaunch(QUANTA);

}

void TIM2_IRQHandler(void){

	TIM2->SR &=~SR_UIF;
	pTask2_Profiler++;
}
void motor_run(void)
{
	printf("M \n\r");

}

void valve_open(void){
	printf("valve is starting \n");
}

void valve_close(void){
	printf("valve is closing \n");
}

void motor_stop(void){
	printf("motor stopping \n");
}


