/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "uart.h"
#include "led.h"
#include <stdio.h>
#include <stdint.h>
void motor_run(void);
void valve_open(void);
void valve_close(void);
void motor_stop(void);

#include "stm32f4xx.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int motor_main(void){
	while(1){
		motor_run();
		delay(1);
		motor_stop();
		delay(1);
	}
}
int valve_main(void){
	while(1){
		valve_open();
		delay(1);
		valve_close();
		delay(1);
	}
}
int main(void)
{
	uint32_t volatile start=0U;

	led_init();
	uart_tx_init();
	timebase_init();

	if (start){
		motor_main();
	}
	else{
		valve_main();
	}
	while(1){
		printf("Hello from stm32 \n\r");
	}
    /* Loop forever */
}


void motor_run(void)
{
	printf("Motor is starting \n");

}

void valve_open(void){
	printf("valve is starting \n");
}

void valve_close(void){
	printf("valve is closing \n");
}

void motor_stop(void){
	printf("motor stopping \n");
}
